version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: testdb123
    ports:
      - 5432:5432

  wanderlust:
    image: wanderlust:latest
    restart: always
    ports:
      - 3030:3030
